// <auto-generated />
namespace Berg_Book_House.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangeAuthorFromForeignKeyToNormalColumnBookTbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeAuthorFromForeignKeyToNormalColumnBookTbl));
        
        string IMigrationMetadata.Id
        {
            get { return "201809101205013_ChangeAuthorFromForeignKeyToNormalColumnBookTbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
